# Generated by Django 4.2.1 on 2023-05-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='featured',
        ),
    ]
