# Generated by Django 4.2.1 on 2023-05-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_employee_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='featured_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
