# Generated by Django 4.2.1 on 2023-05-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_employee_classified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='featured_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
