# Generated by Django 4.2.1 on 2023-05-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_admin_alter_employee_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Doctor',
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(),
        ),
    ]
